// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CHRnem9VabhD1azXIc-XX78khp5QGzs',
    appId: '1:828619539784:web:a7669243db32a9f7301f7d',
    messagingSenderId: '828619539784',
    projectId: 'spendly-auth',
    authDomain: 'spendly-auth.firebaseapp.com',
    storageBucket: 'spendly-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaZIXmfwUgaXdYrqjGf3zR7hZpr_DIyw',
    appId: '1:828619539784:android:b475eafb2e0aa555301f7d',
    messagingSenderId: '828619539784',
    projectId: 'spendly-auth',
    storageBucket: 'spendly-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYO6ru_b-KQtg6WrdTioI0aTkybqze80Y',
    appId: '1:828619539784:ios:8ec585cc41660c6b301f7d',
    messagingSenderId: '828619539784',
    projectId: 'spendly-auth',
    storageBucket: 'spendly-auth.firebasestorage.app',
    iosBundleId: 'com.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYO6ru_b-KQtg6WrdTioI0aTkybqze80Y',
    appId: '1:828619539784:ios:3cea913de1c02971301f7d',
    messagingSenderId: '828619539784',
    projectId: 'spendly-auth',
    storageBucket: 'spendly-auth.firebasestorage.app',
    iosBundleId: 'com.fincook.fincook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7CHRnem9VabhD1azXIc-XX78khp5QGzs',
    appId: '1:828619539784:web:456f016da4c2aa20301f7d',
    messagingSenderId: '828619539784',
    projectId: 'spendly-auth',
    authDomain: 'spendly-auth.firebaseapp.com',
    storageBucket: 'spendly-auth.firebasestorage.app',
  );

}